In [1]:
import pandas as pd

sensus= {
     'tinggi':[158,170,183,191,155,163,180,158,178],
     'berat':[64,86,84,80,49,59,67,54,67],
     'jk':[
         'pria','pria','pria','pria','wanita','wanita','wanita','wanita','wanita'
     ]
}
sensus_df=pd.DataFrame(sensus)
sensus_df

tinggi  berat      jk
0     158     64    pria
1     170     86    pria
2     183     84    pria
3     191     80    pria
4     155     49  wanita
5     163     59  wanita
6     180     67  wanita
7     158     54  wanita
8     178     67  wanita

In [3]:
import numpy as np

X_train = np.array(sensus_df[['tinggi', 'jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train:\n{X_train}\n')
print(f'y_train:{y_train}')

X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

y_train:[64 86 84 80 49 59 67 54 67]


In [4]:
X_train_transposed=np.transpose(X_train)

print(f'X_train:\n{X_train}\n')
print(f'X_train_transposed:\n{X_train_transposed}')

X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

X_train_transposed:
[[158 170 183 191 155 163 180 158 178]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [5]:
from sklearn.preprocessing import LabelBinarizer

lb= LabelBinarizer()
jk_binarised= lb.fit_transform(X_train_transposed[1])

print(f'jk: {X_train_transposed[1]}\n')
print(f'jk_binarised:\n{jk_binarised}')

jk: ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binarised:
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [6]:
jk_binarised=jk_binarised.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [7]:
X_train_transposed[1]= jk_binarised
X_train=X_train_transposed.transpose()

print(f'X_train:\n{X_train}\n')
print(f'X_train_transposed:\n{X_train_transposed}')

X_train:
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [178 1]]

X_train_transposed:
[[158 170 183 191 155 163 180 158 178]
 [0 0 0 0 1 1 1 1 1]]


In [8]:
from sklearn.neighbors import KNeighborsRegressor

K=3
model=KNeighborsRegressor(n_neighbors=K)
model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [9]:
X_new=np.array([[155,1]])
X_new

array([[155,   1]])

In [10]:
y_pred=model.predict(X_new)
y_pred

array([55.66666667])

In [11]:
X_test=np.array([[168,0],[180,0],[160,1],[169,1]])
y_test=np.array([65,96,52,67])
print(f'X_test:\n{X_test}\n')
print(f'y_train:{y_train}')

X_test:
[[168   0]
 [180   0]
 [160   1]
 [169   1]]

y_train:[64 86 84 80 49 59 67 54 67]


In [12]:
y_pred=model.predict(X_test)
y_pred

array([69.66666667, 72.66666667, 59.        , 70.66666667])

In [13]:
from sklearn.metrics import r2_score

r_squared=r2_score(y_test,y_pred)
print(f'R-squared:{r_squared}')

R-squared:0.39200515796260493


In [14]:
from sklearn.metrics import mean_absolute_error
MAE=mean_absolute_error(y_test, y_pred)
print(f'MAE:{MAE}')

MAE:9.666666666666668


In [15]:
from sklearn.metrics import mean_squared_error
MSE=mean_squared_error(y_test, y_pred)
print(f'MSE:{MSE}')

MSE:157.16666666666663


In [16]:
from scipy.spatial.distance import euclidean

X_train=np.array([[1700,0],[1600,1]])
X_new=np.array([1640,0])

[euclidean(X_new[0],d) for d in X_train]

[1641.097193952875, 1639.488029843463]

In [17]:
X_train = np.array([[1.7,0],[1.6,1]])
X_new = np.array([[1.64,0]])

[euclidean(X_new[0],d) for d in X_train]

[0.06000000000000005, 1.0007996802557444]

In [21]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

In [24]:
X_train=np.array([[1.7,0],[1.6,1]])
X_train_scaled=ss.fit_transform(X_train)
print(f'X_train_scaled:\n{X_train_scaled}\n')

X_new=np.array([[1.64,0]])
X_new_scaled=ss.transform(X_new)
print(f'X_new_scaled:{X_new_scaled}\n')

jarak=[euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'jarak:{jarak}')

X_train_scaled:
[[ 1. -1.]
 [-1.  1.]]

X_new_scaled:[[-0.2 -1. ]]

jarak:[1.2000000000000026, 2.1540659228538006]


In [25]:
X_train=np.array([[1700,0],[1600,1]])
X_train_scaled=ss.fit_transform(X_train)
print(f'X_train_scaled:\n{X_train_scaled}\n')

X_new=np.array([[1640,0]])
X_new_scaled=ss.transform(X_new)
print(f'X_new_scaled:{X_new_scaled}\n')

jarak=[euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'jarak:{jarak}')

X_train_scaled:
[[ 1. -1.]
 [-1.  1.]]

X_new_scaled:[[-0.2 -1. ]]

jarak:[1.2, 2.154065922853802]


In [26]:
X_train=np.array([[158,0],[170,0],[191,0],[155,1],[163,1],[180,1],[158,1],[170,1]])
y_train=np.array([64,86,84,80,49,59,67,54,67])

X_test=np.array([[168,0],[180,0],[160,1],[169,1]])
y_test=np.array([65,96,52,67])

In [32]:
X_train_scaled=ss.fit_transform(X_train)
X_test_scaled=ss.transform(X_test)

print(f'X_train_scaled:\n{X_train_scaled}\n')
print(f'X_test_scaled:\n{X_test_scaled}\n')

X_train_scaled:
[[-0.87349625 -1.29099445]
 [ 0.16175856 -1.29099445]
 [ 1.97345449 -1.29099445]
 [-1.13230995  0.77459667]
 [-0.44214008  0.77459667]
 [ 1.02447091  0.77459667]
 [-0.87349625  0.77459667]
 [ 0.16175856  0.77459667]]

X_test_scaled:
[[-0.0107839  -1.29099445]
 [ 1.02447091 -1.29099445]
 [-0.70095378  0.77459667]
 [ 0.07548733  0.77459667]]



model.fit(X_train_scaled, y_train)
y_pred=model.predict(X_test_scaled)

MAE=mean_absolute_error(y_test, y_pred)
MSE=mean_squared_error(y_test, y_pred)

print(f'MAE:{MAE}')
print(f'MSE:{MSE}')

In [34]:
model.fit(X_train_scaled, y_train) 
y_pred=model.predict(X_test_scaled)

MAE=mean_absolute_error(y_test, y_pred) 
MSE=mean_squared_error(y_test, y_pred)

print(f'MAE:{MAE}') 
print(f'MSE:{MSE}')

ValueError: Found input variables with inconsistent numbers of samples: [8, 9]